local _, addon = ...

-- GENERATED by tools/generate_mount_zones.py -- do not edit by hand.
-- Hand-tuning goes in Overrides.lua (merged at runtime).
--
-- mountID == the C_MountJournal mount id == DB2 Mount.ID (no mapping needed on
-- modern clients). Map coordinates are stored as x*10000, y*10000 (same scale as
-- the sibling repo's ZoneData, so Core.lua's waypoint helpers are shared).
--
-- This file is a placeholder until the generator lands (phase 2): every table is
-- present but empty so the runtime can load and index into it without nil checks.

addon.MountData = {
	build = "0.0.0",
	updated = "1970-01-01",

	-- [uiMapID] = { mountID, ... }
	zones = {},
	-- mountIDs with no home zone (class / racial / PvP / store / promo / profession)
	global = {},

	-- [mountID] = "instance" | "drop" | "vendor" | "quest" | "zonedrop"
	--           | "worldevent" | "achievement" | "profession"
	source = {},
	-- [mountID] = "dungeon" | "raid" | "rare" | "holiday" | ...  (optional)
	subcat = {},
	-- [mountID] = expansionID
	expansion = {},
	-- [mountID] = 0 (Horde) | 1 (Alliance)  -- faction-specific mounts only
	faction = {},
	-- [mountID] = { uiMapID, x*10000, y*10000 }
	points = {},

	-- Obtainability inputs. The generator fills what DB2 exposes; the rest is
	-- curated in Overrides.lua.
	-- [mountID] = achievementID
	achievementID = {},
	-- [mountID] = { factionID, standing }  -- standing: numeric reputation/renown threshold
	repFaction = {},
	-- [mountID] = { npcID, uiMapID, x, y, cost, currencyID }  -- cost in copper when currencyID is nil (gold)
	vendor = {},
}
